DROP DATABASE IF EXISTS DuckShopDB;
CREATE DATABASE DuckShopDB;
USE DuckShopDB;

CREATE TABLE Customer(
customerID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`name`VARCHAR(70) NOT NULL,
`description`VARCHAR(70) NOT NULL,

);